# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'property_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_property_selection(object):
    def setupUi(self, property_selection):
        property_selection.setObjectName("property_selection")
        property_selection.resize(710, 455)
        self.horizontalLayout = QtWidgets.QHBoxLayout(property_selection)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(property_selection)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.property_list = QtWidgets.QListWidget(property_selection)
        self.property_list.setObjectName("property_list")
        self.verticalLayout_3.addWidget(self.property_list)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.add_btn = QtWidgets.QPushButton(property_selection)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.remove_btn = QtWidgets.QPushButton(property_selection)
        self.remove_btn.setObjectName("remove_btn")
        self.verticalLayout.addWidget(self.remove_btn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.confirm_btn = QtWidgets.QPushButton(property_selection)
        self.confirm_btn.setObjectName("confirm_btn")
        self.verticalLayout.addWidget(self.confirm_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(property_selection)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.selected_property_list = QtWidgets.QListWidget(property_selection)
        self.selected_property_list.setObjectName("selected_property_list")
        self.verticalLayout_2.addWidget(self.selected_property_list)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(property_selection)
        QtCore.QMetaObject.connectSlotsByName(property_selection)

    def retranslateUi(self, property_selection):
        _translate = QtCore.QCoreApplication.translate
        property_selection.setWindowTitle(_translate("property_selection", "静态属性选择"))
        self.label.setText(_translate("property_selection", "可选静态属性"))
        self.add_btn.setText(_translate("property_selection", "→添加"))
        self.remove_btn.setText(_translate("property_selection", "←移出"))
        self.confirm_btn.setText(_translate("property_selection", "确认"))
        self.label_2.setText(_translate("property_selection", "已选静态属性"))
