# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tool_select(object):
    def setupUi(self, Tool_select):
        Tool_select.setObjectName("Tool_select")
        Tool_select.setWindowModality(QtCore.Qt.ApplicationModal)
        Tool_select.resize(345, 341)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Users/VJ/Desktop/屏幕截图 2022-04-19 094336.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Tool_select.setWindowIcon(icon)
        Tool_select.setAccessibleName("")
        self.widget = QtWidgets.QWidget(Tool_select)
        self.widget.setGeometry(QtCore.QRect(10, 10, 331, 321))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search = QtWidgets.QLabel(self.widget)
        self.search.setObjectName("search")
        self.horizontalLayout.addWidget(self.search)
        self.search_bar = QtWidgets.QLineEdit(self.widget)
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout.addWidget(self.search_bar)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)

        self.retranslateUi(Tool_select)
        QtCore.QMetaObject.connectSlotsByName(Tool_select)

    def retranslateUi(self, Tool_select):
        _translate = QtCore.QCoreApplication.translate
        Tool_select.setWindowTitle(_translate("Tool_select", "工具箱"))
        self.search.setText(_translate("Tool_select", "搜索"))
